import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:trios/modpacks/modpack_format.dart';
import 'package:trios/modpacks/modpack_link_codec.dart';

// Regenerate with --dart-define=UPDATE_MODPACK_GOLDENS=true, then copy the
// golden JSON files and relay_payloads.json unchanged to TriLink/tests/golden.
void main() {
  test('TriLink payload fixtures are generated by the TriOS codec', () {
    final fixtures =
        Directory('test/modpacks/golden')
            .listSync()
            .whereType<File>()
            .where(
              (file) =>
                  file.path.endsWith('.json') &&
                  !file.path.endsWith('relay_payloads.json'),
            )
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));
    final payloads = <String, Object?>{};
    for (final file in fixtures) {
      final definition = decodeModpackDefinition(
        jsonDecode(file.readAsStringSync()),
      );
      payloads[file.uri.pathSegments.last] = {
        'payload': encodeModpackPayload(definition),
        'definition': canonicalModpackMap(definition),
      };
    }
    final manifest = File('test/modpacks/golden/relay_payloads.json');
    if (const bool.fromEnvironment('UPDATE_MODPACK_GOLDENS')) {
      manifest.writeAsStringSync(
        '${const JsonEncoder.withIndent('  ').convert(payloads)}\n',
      );
    }
    expect(jsonDecode(manifest.readAsStringSync()), payloads);
  });
}
